# Generated by Django 4.2.6 on 2024-03-23 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WabaChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("channel_name", models.CharField(max_length=64)),
                ("channel_phone", models.CharField(max_length=13)),
                (
                    "default_sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="default_sector",
                        to="chat.sector",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
