# Generated by Django 4.2 on 2023-04-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_whatsapppost"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="send_by_operator",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="whatsapp_message_id",
            field=models.CharField(default="", max_length=264),
        ),
        migrations.AlterField(
            model_name="message",
            name="status",
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_phone_number", models.CharField(max_length=13)),
                ("customer_name", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("messages", models.ManyToManyField(to="chat.message")),
            ],
        ),
    ]
