# Generated by Django 5.0.3 on 2024-03-23 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_wabachannel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wabachannel",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
