# Generated by Django 5.0.3 on 2024-03-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_rename_update_at_wabachannel_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="wabachannel",
            name="channel_external_id",
            field=models.CharField(default="", max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="wabachannel",
            name="channel_phone",
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
