# Generated by Django 4.2 on 2023-05-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_message_send_by_operator_message_whatsapp_message_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="media_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="type",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
