# Generated by Django 4.2 on 2023-05-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_message_media_id_message_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="media",
            field=models.FileField(blank=True, null=True, upload_to="media"),
        ),
    ]
