# Generated by Django 5.0.3 on 2024-04-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_wabachannel_channel_external_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="attendance_channel",
            field=models.CharField(default="", max_length=13),
        ),
    ]
