# Generated by Django 5.0.3 on 2024-05-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_attendance_attendance_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="last_message_was_sent_by_operator",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="unread_messages_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
