# Generated by Django 4.2 on 2023-05-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_message_media"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=46)),
                ("last_name", models.CharField(max_length=46)),
                ("phone", models.CharField(max_length=20)),
                ("type", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="message",
            name="contacts",
            field=models.ManyToManyField(related_name="contacts", to="chat.contact"),
        ),
    ]
