# Generated by Django 5.0.3 on 2024-07-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="failed_reason",
            field=models.CharField(default="", max_length=128),
        ),
    ]
