# Generated by Django 4.1.4 on 2023-06-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_remove_contact_first_name_remove_contact_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
