# Generated by Django 4.1.4 on 2023-07-05 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_alter_message_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="context",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chat.message",
            ),
        ),
    ]
