# Generated by Django 5.0.3 on 2024-07-09 22:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_message_failed_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="hsm_body",
            field=models.TextField(default="", max_length=1024),
        ),
        migrations.AddField(
            model_name="message",
            name="hsm_buttons",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=25),
                blank=True,
                null=True,
                size=8,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="hsm_footer",
            field=models.CharField(default="", max_length=60),
        ),
        migrations.AddField(
            model_name="message",
            name="hsm_header",
            field=models.CharField(default="", max_length=60),
        ),
        migrations.AlterField(
            model_name="message",
            name="whatsapp_message_id",
            field=models.CharField(max_length=128),
        ),
    ]
