# Generated by Django 4.1.4 on 2023-07-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_message_context"),
    ]

    operations = [
        migrations.CreateModel(
            name="HighStructuredMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("body", models.TextField(max_length=1052)),
            ],
        ),
    ]
