# Generated by Django 5.0.3 on 2024-07-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_message_hsm_body_message_hsm_buttons_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="hsm_body",
        ),
        migrations.AlterField(
            model_name="message",
            name="hsm_footer",
            field=models.CharField(blank=True, default="", max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="hsm_header",
            field=models.CharField(blank=True, default="", max_length=60, null=True),
        ),
    ]
