# Generated by Django 4.1.4 on 2023-07-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_highstructuredmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buttons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.CharField(max_length=96)),
            ],
        ),
        migrations.AddField(
            model_name="highstructuredmessage",
            name="footer",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="highstructuredmessage",
            name="header",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="highstructuredmessage",
            name="buttons",
            field=models.ManyToManyField(blank=True, null=True, to="chat.buttons"),
        ),
    ]
