# Generated by Django 5.0.3 on 2024-07-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_remove_message_chat_messag_attenda_14cc48_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="reaction",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
