# Generated by Django 4.1.4 on 2023-07-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_buttons_highstructuredmessage_footer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="highstructuredmessage",
            name="body_variables_quantitty",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="highstructuredmessage",
            name="header_variables_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
