# Generated by Django 4.1.4 on 2023-07-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_highstructuredmessage_body_variables_quantitty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="highstructuredmessage",
            name="buttons",
            field=models.ManyToManyField(to="chat.buttons"),
        ),
    ]
