# Generated by Django 5.0.3 on 2024-07-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_attendance_reaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="reaction",
        ),
        migrations.AddField(
            model_name="message",
            name="reaction",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
