# Generated by Django 4.1.4 on 2023-07-16 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0013_alter_highstructuredmessage_buttons"),
    ]

    operations = [
        migrations.RenameField(
            model_name="highstructuredmessage",
            old_name="body_variables_quantitty",
            new_name="body_variables_quantity",
        ),
    ]
