# Generated by Django 5.0.3 on 2024-07-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0014_alter_message_failed_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="highstructuredmessage",
            name="category",
            field=models.CharField(
                choices=[
                    ("marketing", "MARKETING"),
                    ("utility", "UTILITY"),
                    ("authentication", " AUTHENTICATION"),
                ],
                default="pending",
                max_length=14,
            ),
        ),
        migrations.AddField(
            model_name="highstructuredmessage",
            name="external_template_id",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="highstructuredmessage",
            name="rejected_reason",
            field=models.CharField(default="", max_length=96),
        ),
        migrations.AddField(
            model_name="highstructuredmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "PENDING"),
                    ("rejected", "REJECTED"),
                    ("approved", "APPROVED"),
                    ("disabled", "DISABLED"),
                    ("paused", "DISABLED"),
                ],
                default="marketing",
                max_length=14,
            ),
        ),
    ]
