# Generated by Django 4.1.4 on 2023-07-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "chat",
            "0014_rename_body_variables_quantitty_highstructuredmessage_body_variables_quantity",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="highstructuredmessage",
            name="language_code",
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
