# Generated by Django 5.0.3 on 2024-07-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0015_highstructuredmessage_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="highstructuredmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "PENDING"),
                    ("rejected", "REJECTED"),
                    ("approved", "APPROVED"),
                    ("disabled", "DISABLED"),
                    ("paused", "PAUSED"),
                ],
                default="marketing",
                max_length=14,
            ),
        ),
    ]
