# Generated by Django 4.1.4 on 2023-08-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0015_highstructuredmessage_language_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="is_close",
            field=models.BooleanField(default=False),
        ),
    ]
