# Generated by Django 5.0.3 on 2024-07-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0016_alter_highstructuredmessage_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="highstructuredmessage",
            name="category",
            field=models.CharField(
                choices=[
                    ("marketing", "MARKETING"),
                    ("utility", "UTILITY"),
                    ("authentication", " AUTHENTICATION"),
                ],
                default="MARKETING",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="highstructuredmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "PENDING"),
                    ("rejected", "REJECTED"),
                    ("approved", "APPROVED"),
                    ("disabled", "DISABLED"),
                    ("paused", "PAUSED"),
                ],
                default="pending",
                max_length=14,
            ),
        ),
    ]
