# Generated by Django 4.1.4 on 2023-08-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0016_attendance_closed_at_attendance_is_close"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="customer_name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
