# Generated by Django 4.1.4 on 2023-08-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0017_alter_attendance_customer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="origin_identifier",
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
