# Generated by Django 4.1.4 on 2023-08-16 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0018_message_origin_identifier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="messages",
        ),
        migrations.AddField(
            model_name="message",
            name="attendance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="chat.attendance",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="origin_identifier",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
