# Generated by Django 5.1.3 on 2024-12-20 22:17

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0018_alter_highstructuredmessage_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="edited_name",
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None, unique=True
            ),
        ),
    ]
