# Generated by Django 4.1.4 on 2023-08-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0019_remove_attendance_messages_message_attendance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
