# Generated by Django 5.1.3 on 2025-01-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0019_contact_edited_name_contact_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="highstructuredmessage",
            name="rejected_reason",
            field=models.CharField(blank=True, default="", max_length=96, null=True),
        ),
    ]
