# Generated by Django 4.1.4 on 2023-08-20 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0020_alter_contact_phone_alter_contact_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="is_close",
            new_name="is_closed",
        ),
    ]
