# Generated by Django 4.1.4 on 2023-08-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0021_rename_is_close_attendance_is_closed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="contacts",
            field=models.ManyToManyField(
                blank=True, related_name="contacts", to="chat.contact"
            ),
        ),
    ]
