# Generated by Django 4.1.4 on 2023-09-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0022_alter_message_contacts"),
    ]

    operations = [
        migrations.CreateModel(
            name="sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=54)),
            ],
        ),
    ]
