# Generated by Django 4.1.4 on 2023-09-16 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0023_sector"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.sector",
            ),
        ),
    ]
