# Generated by Django 4.1.4 on 2023-10-09 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0024_attendance_sector"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Buttons",
            new_name="Button",
        ),
    ]
