# Generated by Django 4.2.6 on 2023-10-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0026_attendance_updated_at_button_created_at_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["attendance"], name="chat_messag_attenda_14cc48_idx"
            ),
        ),
    ]
