# Generated by Django 4.2.6 on 2023-10-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0029_remove_message_chat_messag_id_db6e10_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
    ]
