# Generated by Django 4.2.6 on 2023-10-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0030_alter_message_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsapppost",
            name="body",
            field=models.CharField(max_length=4000),
        ),
    ]
