# Generated by Django 4.2.6 on 2023-10-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0031_alter_whatsapppost_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="highstructuredmessage",
            name="buttons",
            field=models.ManyToManyField(blank=True, null=True, to="chat.button"),
        ),
    ]
