# Generated by Django 4.2.6 on 2023-11-04 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("display_name", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("role", models.IntegerField(default=1)),
                ("inactivated_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "sectors",
                    models.ManyToManyField(
                        related_name="user_sector", to="chat.sector"
                    ),
                ),
                (
                    "sectors_transfer",
                    models.ManyToManyField(
                        blank=True,
                        related_name="user_transfer_sector",
                        to="chat.sector",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
