# Generated by Django 4.2.6 on 2023-11-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_sectors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="inactivated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
