# Generated by Django 5.0.3 on 2024-04-27 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_user_options_user_date_joined_user_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="sectors",
        ),
        migrations.RemoveField(
            model_name="user",
            name="sectors_transfer",
        ),
    ]
