# Generated by Django 5.2.5 on 2025-08-16 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_company_organization_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'CNPJ must have 14 digits')]),
        ),
    ]
