# Generated by Django 5.2.5 on 2025-08-16 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_organization_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'CNPJ must have 14 digits')]),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(condition=models.Q(('cnpj__regex', '^\\d{14}$'), ('cnpj__isnull', True), _connector='OR'), name='cnpj_format_check'),
        ),
    ]
