# Generated by Django 5.2.5 on 2025-08-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_organization_cnpj_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organization',
            name='cnpj_format_check',
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(condition=models.Q(('cnpj__regex', '^[0-9]{14}$')), name='cnpj_format_check'),
        ),
    ]
